sudo: required
language: python
services:
  - docker

script:
  - docker image build -t raj-mistry/847-helloworld .

after_success:
  #log in to docker CLI
  - echo "PASSWORD" | docker login -u raj225 --password-stdin
  #take built images and push to DOcker hub
  - docker push raj225/847-helloworld
  #test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "dtest"
  env: "Dtest-env-1"
  bucket_name: "elasticbeanstalk-ca-central-1-521457061038"
  on:
    all_braches: true
  access_key_id: "AWSID"
  secret_access_key: "AWSACCESS"
